/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AboutPage {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CheckIn {
    }
    interface ColorPicker {
        "target": any;
    }
    interface EditHabit {
    }
    interface NewHabit {
    }
    interface YearCalendar {
        "date": string;
    }
}
declare global {
    interface HTMLAboutPageElement extends Components.AboutPage, HTMLStencilElement {
    }
    var HTMLAboutPageElement: {
        prototype: HTMLAboutPageElement;
        new (): HTMLAboutPageElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCheckInElement extends Components.CheckIn, HTMLStencilElement {
    }
    var HTMLCheckInElement: {
        prototype: HTMLCheckInElement;
        new (): HTMLCheckInElement;
    };
    interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {
    }
    var HTMLColorPickerElement: {
        prototype: HTMLColorPickerElement;
        new (): HTMLColorPickerElement;
    };
    interface HTMLEditHabitElement extends Components.EditHabit, HTMLStencilElement {
    }
    var HTMLEditHabitElement: {
        prototype: HTMLEditHabitElement;
        new (): HTMLEditHabitElement;
    };
    interface HTMLNewHabitElement extends Components.NewHabit, HTMLStencilElement {
    }
    var HTMLNewHabitElement: {
        prototype: HTMLNewHabitElement;
        new (): HTMLNewHabitElement;
    };
    interface HTMLYearCalendarElement extends Components.YearCalendar, HTMLStencilElement {
    }
    var HTMLYearCalendarElement: {
        prototype: HTMLYearCalendarElement;
        new (): HTMLYearCalendarElement;
    };
    interface HTMLElementTagNameMap {
        "about-page": HTMLAboutPageElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "check-in": HTMLCheckInElement;
        "color-picker": HTMLColorPickerElement;
        "edit-habit": HTMLEditHabitElement;
        "new-habit": HTMLNewHabitElement;
        "year-calendar": HTMLYearCalendarElement;
    }
}
declare namespace LocalJSX {
    interface AboutPage {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface CheckIn {
    }
    interface ColorPicker {
        "target"?: any;
    }
    interface EditHabit {
    }
    interface NewHabit {
    }
    interface YearCalendar {
        "date"?: string;
        "onCalendarSelected"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "about-page": AboutPage;
        "app-home": AppHome;
        "app-root": AppRoot;
        "check-in": CheckIn;
        "color-picker": ColorPicker;
        "edit-habit": EditHabit;
        "new-habit": NewHabit;
        "year-calendar": YearCalendar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-page": LocalJSX.AboutPage & JSXBase.HTMLAttributes<HTMLAboutPageElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "check-in": LocalJSX.CheckIn & JSXBase.HTMLAttributes<HTMLCheckInElement>;
            "color-picker": LocalJSX.ColorPicker & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
            "edit-habit": LocalJSX.EditHabit & JSXBase.HTMLAttributes<HTMLEditHabitElement>;
            "new-habit": LocalJSX.NewHabit & JSXBase.HTMLAttributes<HTMLNewHabitElement>;
            "year-calendar": LocalJSX.YearCalendar & JSXBase.HTMLAttributes<HTMLYearCalendarElement>;
        }
    }
}
